spring.application.name=Forproject

#  DATABASE CONFIG
spring.datasource.url=jdbc:mysql://root:GESfZkmEzrMoFYYgnNJxfyuHuPrOleuf@switchback.proxy.rlwy.net:43709/railway
spring.datasource.username=root
spring.datasource.password=GESfZkmEzrMoFYYgnNJxfyuHuPrOleuf

#  JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


server.port=3366

#  MULTIPART FILE UPLOAD
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#  OPTIONAL (better debugging)
logging.level.org.springframework=INFO

# EMAIL API CONFIGURATION (Brevo / HTTP)
brevo.api.key=YOUR_BREVO_API_KEY_HERE
brevo.sender.email=nikhilmadineedi@gmail.com
brevo.sender.name=Course Sphere
